---
title: "Working with Tabular Data"
subtitle: Analysis of Wines
Author: Anzhilov Shorena
output:
  html_document:
    df_print: paged
Date: r Sys.Date()
---

```{r, echo=FALSE, cashe=FALSE}
df.wines <- read.csv(
   file = "https://s3.us-east-2.amazonaws.com/artificium.us/datasets/whitewines.csv",
   stringsAsFactors = FALSE,
   header = TRUE
)

totalWines <-nrow(df.wines)
alcoholContentOver11 <- round(mean(df.wines$alcohol > 11, na.rm = TRUE) *100, 1)
highestAlcoholContent <- max(df.wines$alcohol, na.rm = TRUE)
```

#### There are a total of **`r totalWines`** wines in this data set. **`r alcoholContentOver11`**% of the wines have an alcohol content over 11%. The highest alcohol content of any wine is **`r highestAlcoholContent`**%.

#### The scatter plot below illustrates the correlation between alcohol and sugar content.

```{r, echo=FALSE}
plot(df.wines$residual.sugar, df.wines$alcohol, 
      main = "Sugar vs Alcohol Content", 
      xlab = "Sugar", 
      ylab = "Alcohol", 
      col = "black", 
      pch = 1)
```